// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Apple: typeof import('./src/components/Apple.vue')['default']
    Code: typeof import('./src/components/Code.vue')['default']
    ColorCard: typeof import('./src/components/ColorCard.vue')['default']
    Demo: typeof import('./src/components/demo.vue')['default']
    LifeShare: typeof import('./src/components/LifeShare.vue')['default']
    Moon: typeof import('./src/components/Moon.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBackTop: typeof import('naive-ui')['NBackTop']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NImage: typeof import('naive-ui')['NImage']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPopover: typeof import('naive-ui')['NPopover']
    NSpace: typeof import('naive-ui')['NSpace']
    NTag: typeof import('naive-ui')['NTag']
    ProjectList: typeof import('./src/components/ProjectList.vue')['default']
    ScrollRow: typeof import('./src/components/scrollRow.vue')['default']
    Svg: typeof import('./src/components/Svg.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
  }
}

export { }
