// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AnimeSbtn: typeof import('./src/components/anime/Sbtn.vue')['default']
    AnimeWaterDrop: typeof import('./src/components/anime/WaterDrop.vue')['default']
    D3Line: typeof import('./src/components/D3/line.vue')['default']
    EchartsDoubleLine: typeof import('./src/components/echarts/doubleLine.vue')['default']
    EchartsLine: typeof import('./src/components/echarts/line.vue')['default']
    EchartsLine2: typeof import('./src/components/echarts/line2.vue')['default']
    EchartsPie: typeof import('./src/components/echarts/pie.vue')['default']
    G2plotDoubleLine: typeof import('./src/components/g2plot/doubleLine.vue')['default']
    GProgress: typeof import('./src/components/GProgress.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPopover: typeof import('naive-ui')['NPopover']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTag: typeof import('naive-ui')['NTag']
    NWatermark: typeof import('naive-ui')['NWatermark']
    ToastMessage: typeof import('./src/components/ToastMessage.vue')['default']
    Video: typeof import('./src/components/Video/index.vue')['default']
    VideoBoard: typeof import('./src/components/Video/board.vue')['default']
  }
}

export { }
