<template>
  <div class="bot-bg">
    <div 
      class="bot-box " 
      ref="bot" 
      @mousemove="handleMouseMove"
    >
      <div class="eye"></div>
      <div class="eye"></div>
      <div class="mouth"></div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount } from "vue";

const bot = ref<HTMLDivElement | null>(null);
let bounceInterval: number | null = null;

// 控制鼠标移动事件
const handleMouseMove = (event: MouseEvent) => {
  if (!bot.value) return;
  const rect = bot.value.getBoundingClientRect();
  const centerX = rect.left + rect.width / 2;
  const centerY = rect.top + rect.height / 2;
  const deltaX = event.clientX - centerX;
  const deltaY = event.clientY - centerY;
  bot.value.style.transform = `translate(${deltaX * 0.3}px, ${deltaY * 0.3}px) rotate(${deltaX * 0.15}deg)`;
};

// 设置不定时弹跳效果
const startBouncing = () => {
  if (!bot.value) return;

  bounceInterval = window.setInterval(() => {
    bot.value?.classList.add("bouncing");
    setTimeout(() => {
      bot.value?.classList.remove("bouncing");
    }, 500);
  }, 2000);
};

// 清理定时器
onMounted(startBouncing);
onBeforeUnmount(() => {
  if (bounceInterval) clearInterval(bounceInterval);
});
</script>

<style lang="scss" scoped>
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

.bot-bg {
  height: 100vh;
  width: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  background: linear-gradient(to bottom, #e0f7fa, #4facfe);
  perspective: 1000px;

  .bot-box {
    width: 120px;
    height: 90px;
    background: linear-gradient(to right, #4facfe, #00f2fe);
    border-radius: 40px;
    box-shadow: 0 20px 30px rgba(0, 0, 0, 0.2);
    display: flex;
    justify-content: center;
    align-items: center;
    cursor: pointer;
    transform-style: preserve-3d;
    transition: transform 0.3s ease-out;
    position: relative;

    // 弹跳形变
    &.bouncing {
      animation: bounce 0.5s cubic-bezier(0.25, 1, 0.5, 1);
    }

    // 阴影效果
    &::after {
      content: '';
      position: absolute;
      bottom: -10px;
      left: 50%;
      transform: translateX(-50%);
      width: 80px;
      height: 15px;
      background: rgba(0, 0, 0, 0.2);
      border-radius: 50%;
      filter: blur(5px);
    }

    .eye {
      width: 20px;
      height: 20px;
      background: #ffffff;
      border-radius: 50%;
      margin: 20px 5px;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
    }

    .mouth {
      width: 40px;
      height: 10px;
      background: #ffffff;
      border-radius: 5px;
      position: absolute;
      bottom: 20px;
    }
  }
}

// 动画关键帧
@keyframes bounce {
  0%, 100% {
    transform: translateY(0) scale(1);
  }
  50% {
    transform: translateY(-30px) scale(1.1, 0.9);
  }
}


.heartbeat {
	-webkit-animation: heartbeat 1.5s ease-in-out infinite both;
	        animation: heartbeat 1.5s ease-in-out infinite both;
}

/* ----------------------------------------------
 * Generated by Animista on 2024-12-28 11:55:5
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation heartbeat
 * ----------------------------------------
 */
 @-webkit-keyframes heartbeat {
  from {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-transform-origin: center center;
            transform-origin: center center;
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  10% {
    -webkit-transform: scale(0.91);
            transform: scale(0.91);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  17% {
    -webkit-transform: scale(0.98);
            transform: scale(0.98);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  33% {
    -webkit-transform: scale(0.87);
            transform: scale(0.87);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  45% {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
}
@keyframes heartbeat {
  from {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-transform-origin: center center;
            transform-origin: center center;
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  10% {
    -webkit-transform: scale(0.91);
            transform: scale(0.91);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  17% {
    -webkit-transform: scale(0.98);
            transform: scale(0.98);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  33% {
    -webkit-transform: scale(0.87);
            transform: scale(0.87);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  45% {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
}

</style>